### ISSUE TITLE
Pretrained model is valid only for english speechs?

### ISSUE THREAD

**Issue by qinxunhui** [santi-pdp/segan_pytorch#10]
if there is another speech but not with English, we must train model again?  thanks.

**Comment by santi-pdp** [comment]
Yes, but loading the English weights might be quite useful as we investigated in this work: https://arxiv.org/abs/1712.06340

**Comment by theAayushbajaj** [comment]
What sampling rate and other voice params should the audio be (in other language) to get a result on pretrained weights?
I tried using pretrained weights and the enhanced audio file is blank.
