### ISSUE TITLE
WSEGAN weights

### ISSUE THREAD

**Issue by miraodasilva** [santi-pdp/segan_pytorch#13]
Hi!

I would be very interested in using a pre-trained of WSEGAN. However, from what I can see you have not released the pre-trained weights for this version of your model, only for SEGAN. Do you plan to release these at any point?

Thanks a lot.

**Comment by betegon** [comment]
Did you obtain them @miraodasilva ??

**Comment by miraodasilva** [comment]
No, unfortunately not.
