### ISSUE TITLE
Inference Speed

### ISSUE THREAD

**Issue by deepconsc** [santi-pdp/segan_pytorch#20]
Hey!
Amazing work, gonna test it.

I've one question prior to testing - how fast is enhancement inference? 
Let's say - with perspective of input length.

**Comment by santi-pdp** [comment]
Hello,

in the SEGAN+ paper (https://www-sciencedirect-com.recursos.biblioteca.upc.edu/science/article/pii/S0167639319301359) we detail why we chose to stride aggressively with less layers than in the first SEGAN design. One of the reasons is to make it more efficient, as I cite below (section 6.1.1).

_In this first level of experiments, we determine the effectiveness of increasing kernel stride in terms of both stability and performance, in addition to the degradations in performance associated with smaller kernel widths (V1.1 and V1.2, Table 1). This condition also makes G more efficient, yielding a generation process that is 1.7 times faster than real time on a CPU and 17 times faster on a GPU._

Hope this helps!

**Comment by santi-pdp** [comment]
Also let me clarify that the input length, it it is too large (as we also comment in the paper), you break down into subsequences at batch dimension (that is done in the SEGAN instance in the code) and that parallelizes the inference per pieces, which does not degrade the result.
