### ISSUE TITLE
Why the stride of convolution layer in generator is 4?

### ISSUE THREAD

**Issue by JUiscoming** [santi-pdp/segan_pytorch#26]
In your paper [LINK](https://arxiv.org/pdf/1703.09452.pdf), I readed G is composed of ~ **strides of N =2** in page 3, but strides are 4 in your code. Because of the performance?

**Comment by USER-5** [comment]
If I understand correctly, the original SEGAN implementation had a stride length of 2, but the improved SEGAN+ [link](https://www.sciencedirect.com/science/article/pii/S0167639319301359) has a stride length of 4, as well as some other tweaked hyper parameters.

**Comment by JUiscoming** [comment]
Thank you for your kindness :)
