### ISSUE TITLE
ADD LICENSE 

### ISSUE THREAD

**Issue by betegon** [santi-pdp/segan_pytorch#27]
Hi @santi-pdp 

First of all, congrats for putting out such an amazing work! 

I have been experimenting with the **segan** tensorflow repository, and now I am looking to do some testing on this one.

The other repo has a license, found [here](https://github.com/santi-pdp/segan/blob/master/LICENCE), so I imagine this being a related work it will have the same license, and because of that you forgot to add it.

Anyway, **could you please add a license to this repository?** 
This way we will know how can we use it! _(As you know, if no license is attached to the code, the only thing I can do is view the code but not modify anything)_

Thanks a lot for your time and effort.

Looking forward to hear from you soon,

Miguel.

**PD:** ¡Saludos desde Santander!

**Comment by santi-pdp** [comment]
Hi @betegon,

this was corrected, I don't know why it was not publicly in the repo but I used to have it when making this project as far as I remember.

Santi

PD: ¡Saludos desde Barcelona!

**Comment by betegon** [comment]
Thank you for answering back so quickly!

Also thank you for realising it with MIT license.


Buenas noches desde la Universidad de Cantabria y espero que todo vaya bien por Barcelona.
